apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.type }}-echoserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: echo-server-deployment
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: {{ .Values.echoservice.image }}
          imagePullPolicy: {{ .Values.echoservice.imagePullPolicy }}
          name: echoserver
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"