apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  customer: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: echo-server
      customer: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: echo-server
        customer: {{ .Release.Namespace }}
    spec:
      containers:
        - image: {{ .Values.echoservice.image }}
          imagePullPolicy: {{ .Values.echoservice.imagePullPolicy }}
          name: echo-server
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"