apiVersion: v1
kind: Service
metadata:
  name: service-1-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: service-1-{{ .Release.Namespace }}
    customer: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: service-1
    customer: { { .Release.Namespace } }
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: service-1