apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.type }}-echo-server
  namespace: {{ .Release.Namespace }}
  customer: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8004
      targetPort: echo-server
      name: echo-server
      protocol: TCP
  type: ClusterIP
  selector:
    app: echo-server
    customer: {{ .Release.Namespace }}