apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.type }}-echo-server
  namespace: {{ .Release.Namespace }}
  customer: {{ .Release.Namespace }}
  labels:
    name: service-2-{{ .Release.Namespace }}
    customer: { { .Release.Namespace } }
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: echo-server
      name: echo-server
      protocol: TCP
  selector:
    app: echo-server
    customer: {{ .Release.Namespace }}