apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-{{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: service-2
      customer: {{ .Release.Namespace }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-2
        customer: {{ .Release.Namespace }}
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: config-vol
              mountPath: /etc/nginx/
      volumes:
        - name: config-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf