apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-service-2
  namespace: {{ .Release.Namespace }}
  labels:
    type: "{{ .Values.type }}"
    customer: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /{{ .Release.Namespace }}/service-2/(.*) # namespace name so it can be reached via minikube/{{ .Release.Namespace }}
            pathType: Prefix
            backend:
              service:
                name: service-2-{{ .Release.Namespace }}
                port:
                  name: service-2-port