apiVersion: v1
kind: Service
metadata:
  name: service-2-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: service-2-{{ .Release.Namespace }}
    customer: "{{ .Release.Namespace }}"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      name: service-2-port
  selector:
    app: service-2
    customer: "{{ .Release.Namespace }}"

#------------------------
#apiVersion: v1
#kind: Service
#metadata:
#  name: yari-api-portal-{{ .Values.dprData.projectId }}
#  namespace: {{ .Release.Namespace }}
#  labels:
#    name: yari-api-portal-{{ .Values.dprData.projectId }}
#    dprType: "{{ .Values.dprData.dprType }}"
#    projectId: "{{ .Values.dprData.projectId }}"
#spec:
#  type: ClusterIP
#  ports:
#    - port: 8004
#      targetPort: yari-api-portal
#      name: yari-api-portal
#      protocol: TCP
#  selector:
#    app: yari-api-portal
#    projectId: "{{ .Values.dprData.projectId }}"