apiVersion: v1
kind: Service
metadata:
  name: service-2-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: service-2-{{ .Release.Namespace }}
    customer: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      name: service-2-port
      protocol: TCP
  selector:
    app: service-2
    customer: {{ .Release.Namespace }}